### ISSUE TITLE
Mapping nullable enum to int?

### ISSUE THREAD

**Issue by marcWF2** [TinyMapper/TinyMapper#11]
With TinyMapper you can implicit map an enum to an int, but when you map a nullable to a nullable int (and visaversa) the result is always null. Is it possible to add this to the core so I have not to write a custom convertor for every object containing an enum?

Thanks!

**Comment by GSerjo** [comment]
I'll take a look and fix it..

**Comment by GSerjo** [comment]
Solved in 2.0.1, could you please the newest version on the nuget server

**Comment by marcWF2** [comment]
Thanks Sergey, it's working both directions!
Great Mapper (after the struggling with Automapper and ValueInjector).

Marc

**Comment by GSerjo** [comment]
You're wellcome and thanks for your feedback :)
