### ISSUE TITLE
run time error

### ISSUE THREAD

**Issue by lijaso** [TinyMapper/TinyMapper#14]
Hi Serjo,

Really love this tool, simple and elegant. I copied the sample code to a console app, but got a run time error, the screenshot is attached. the environment is vs2013 .net 4.51. Not sure if I missed something.

Thanks in advance,

JL
![tinymapper_error](https://cloud.githubusercontent.com/assets/2891278/8844473/b6fc9e92-3158-11e5-8d4c-cca9a0eac9b4.PNG)

**Comment by GSerjo** [comment]
Hi lijaso,

Just move `Person` and `PersonDto` from `Program` class. `Program` clas is private so unable to access to `Persorn` and `PersonDto`

**Comment by lijaso** [comment]
Thanks a lot Serjo. Moving the classes to a separate file works. 

Cheers,
