### ISSUE TITLE
Exception while mapping nested base member

### ISSUE THREAD

**Issue by teknogecko** [TinyMapper/TinyMapper#17]
We have problems mapping an instance (CreateCampaignProcess) of a base type (CampaignProcessBase) that contains a member that has an instance (PromotionCampaign) of a base type (CampaignBase) as well. 

![campaignprocess-tinymap-exception-watch](https://cloud.githubusercontent.com/assets/5380226/9763369/7b2c2082-5709-11e5-8ac3-24225efabfdd.png)

Mapping code:
```request.Process = TinyMapper.Map<CreateCampaignProcess, PublishCampaignProcess>((CreateCampaignProcess)process);```

    [NullReferenceException: Object reference not set to an instance of an object.]
    xxx.Service.ServiceModel.CampaignBase.set_Title(String value) +53
    DynamicTinyMapper.ClassMappers.Mapper70ac31ec444945129528a9c38a0353de.MapClass(CampaignBase , CampaignBase ) +34
    Nelibur.ObjectMapper.Mappers.Classes.ClassMapper`2.MapCore(TSource source, TTarget target) +60
    Nelibur.ObjectMapper.Mappers.MapperOf`2.MapCore(Object source, Object target) +107
    DynamicTinyMapper.ClassMappers.Mappercf022320fcf94ca6b5811f838f315f91.MapClass(CreateCampaignProcess , PublishCampaignProcess ) +220
    Nelibur.ObjectMapper.Mappers.Classes.ClassMapper`2.MapCore(TSource source, TTarget target) +60
    Nelibur.ObjectMapper.Mappers.MapperOf`2.MapCore(Object source, Object target) +107
    Nelibur.ObjectMapper.TinyMapper.Map(TSource source, TTarget target) +632

**Comment by GSerjo** [comment]
Could you please give me `CreateCampaignProcess`, `PublishCampaignProcess` with base classes or similar classes? I'll try to reproduce and fix asap

**Comment by teknogecko** [comment]
Hi Sergey,

I've extracted the classes from our solution. Good luck!

Best regards,
Bas

**Comment by GSerjo** [comment]
Thanks, but how can I get it, i.e. there's no attached files? I don't see any classes :(

**Comment by teknogecko** [comment]
Your virusscannner probably got it. I'll send it by wetransfer.

Bas

**Comment by teknogecko** [comment]
What's your email?
