### ISSUE TITLE
How to map IDataReader or IDataRecord to a List<T> or an object

### ISSUE THREAD

**Issue by Behzadkhosravifar** [TinyMapper/TinyMapper#19]
I'm using __TinyMapper__ in my projects as well. That is much faster from famous Mappers such `AutoMapper` and ...
But the problem that I am facing is I can't to convert `IDataReader` to a `List<T>` or `IDataRecord` to an `object`.

I solved this problem by `CodeDOM` library for me. For example now can to Map a `SqlDataReader` to a List of any object, also to a dynamic object. 
But I think this is not a common practice and principles of your code. Again, if you want I can send you my code.

Thanks 

Behzad Khosravi-Far

**Comment by GSerjo** [comment]
Hi Behzad Khosravi-Far,

It'll be excellent if you can send your code, I'll try to fix the issue. `sedot8` on google

**Comment by Behzadkhosravifar** [comment]
Please Give me you Mail Address to send my codes

**Comment by GSerjo** [comment]
Close the issue, after discussion, [Dapper](https://github.com/StackExchange/dapper-dot-net) is a better choice for `IDataReader` mapping.
