### ISSUE TITLE
DateTime? is not mapped in special scenario

### ISSUE THREAD

**Issue by gaclaudiu** [TinyMapper/TinyMapper#25]
[Program.txt](https://github.com/TinyMapper/TinyMapper/files/49950/Program.txt)

I've attached a custom scenario I encountered in which I have type A and Type B , both having 2 properties of type DateTime?  with the same name .

But if I use TinyMapper.Bind before doing the mapping ( I have 2 string properties on the types with different names )  the mapping for DateTime? properties no longer work .

I saw that this is specific to DateTime? properties only. I tried with int? and it works .

I've attached a console application program cs file to reproduce this issue .

Any help would be appreciated .

I'm interested to find out if I'm doing something wrong or if this is a possible bug in TinyMapper .

Cheers,
Claudiu

**Comment by GSerjo** [comment]
Hi Claudiu,

It was a bug, sorry. Fixed in [2.0.8](https://www.nuget.org/packages/TinyMapper/2.0.8) and added a test based on your sample. Thanks!

**Comment by gaclaudiu** [comment]
Cheers mate ! 

We're integrating the new version . 

I'll let you know the feedback after the tests pass.

Thank you !

**Comment by gaclaudiu** [comment]
Everything looks good . 
Bug is fixed, I'll close the issue .

**Comment by GSerjo** [comment]
Thanks a lot :)
