### ISSUE TITLE
calling convention must be varargs

### ISSUE THREAD

**Issue by technicalganesh** [TinyMapper/TinyMapper#26]
Update: The reason could be because of Change Tracking Proxies created by Entity framework instead of creating the instances of the entities directly. The Proxy classes are not being handled by Tiny mapper. It is no other way as of I know to overcome this. Anyone have any Idea?

The original problem I posted some time back:

I am having ASP.Net Entities with their repositories and Viewmodels to get exposed from my Services layer. When I try to Bind any of my entity to viewmodel, I am getting an error with no inner exception but with stack trace

The code which causing the issue is : TinyMapper.Bind<EnterpriseProfile, EnterpriseProfileViewModel>();

Can I have some idea what was the mistake I made?

The exception is as below:

"Message": "An error has occurred."
"ExceptionMessage": "Calling convention must be VarArgs."
"ExceptionType": "System.InvalidOperationException"
"StackTrace": " at System.Reflection.Emit.ModuleBuilder.GetMemberRefToken(MethodBase method, IEnumerable`1 optionalParameterTypes) at System.Reflection.Emit.ModuleBuilder.GetMethodTokenInternal(MethodBase method, IEnumerable`1 optionalParameterTypes, Boolean useMethodDef) at System.Reflection.Emit.ILGenerator.GetMethodToken(MethodBase method, Type[] optionalParameterTypes, Boolean useMethodDef) at System.Reflection.Emit.ILGenerator.EmitCall(OpCode opcode, MethodInfo methodInfo, Type[] optionalParameterTypes) at Nelibur.ObjectMapper.CodeGenerators.CodeGenerator.EmitCall(MethodInfo method) at Nelibur.ObjectMapper.CodeGenerators.CodeGenerator.EmitCall(MethodInfo method, IEmitterType invocationObject, IEmitterType[] arguments) at Nelibur.ObjectMapper.CodeGenerators.Emitters.EmitMethod.EmitterCallMethod.Emit(CodeGenerator generator) at Nelibur.ObjectMapper.CodeGenerators.Emitters.EmitProperty.EmitLoadProperty.Emit(CodeGenerator generator) at Nelibur.ObjectMapper.CodeGenerators.CodeGenerator.EmitCall(MethodInfo method, IEmitterType invocationObject, IEmitterType[] arguments) at Nelibur.ObjectMapper.CodeGenerators.Emitters.EmitMethod.EmitterCallMethod.Emit(CodeGenerator generator) at Nelibur.ObjectMapper.CodeGenerators.Emitters.EmitProperty.EmitStoreProperty.Emit(CodeGenerator generator) at Nelibur.ObjectMapper.CodeGenerators.Emitters.EmitComposite.<>c__DisplayClass1.<Emit>b__0(IEmitter x) at System.Collections.Generic.List`1.ForEach(Action`1 action) at Nelibur.ObjectMapper.CodeGenerators.Emitters.EmitComposite.Emit(CodeGenerator generator) at Nelibur.ObjectMapper.CodeGenerators.Emitters.EmitComposite.<>c__DisplayClass1.<Emit>b__0(IEmitter x) at System.Collections.Generic.List`1.ForEach(Action`1 action) at Nelibur.ObjectMapper.CodeGenerators.Emitters.EmitComposite.Emit(CodeGenerator generator) at Nelibur.ObjectMapper.Mappers.Classes.ClassMapperBuilder.EmitMapClass(TypePair typePair, TypeBuilder typeBuilder) at Nelibur.ObjectMapper.Mappers.Classes.ClassMapperBuilder.BuildCore(TypePair typePair) at Nelibur.ObjectMapper.Mappers.MapperBuilder.Build(TypePair typePair) at Nelibur.ObjectMapper.Mappers.TargetMapperBuilder.Build(TypePair typePair) at Nelibur.ObjectMapper.TinyMapper.Bind[TSource,TTarget]() at Infa.Services.EnterpriseProfileService.GetByAliasName(String aliasName) in e:\Ganesh\InfaCLOUD\Common\Infa.Services\Profile\EnterpriseProfileService.cs:line 26 at Infa.Crop.Web.Controllers.AccountController.<Register>d__29.MoveNext() in e:\Ganesh\InfaCLOUD\Crop\Infa.Crop.Web\Controllers\AccountController.cs:line 358 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"

**Comment by technicalganesh** [comment]
I found this issue not appearing in ExpressMapper I am happy with that. And performance is much better than TinyMapper.

Please improve the TinyMapper, I will try to comeback. Thanks! See you soon...

My Express mapper code....

            var entity = enterpriseProfileRepository.GetByAliasName(aliasName);
            EnterpriseProfileViewModel viewModel = new EnterpriseProfileViewModel();
            Mapper.Map<EnterpriseProfile, EnterpriseProfileViewModel>(entity, viewModel);
            return viewModel;

**Comment by GSerjo** [comment]
Could  you please share your `source` and `target` classes. I'll try to reproduce the issue

**Comment by technicalganesh** [comment]
Simple steps to reproduce....! 

Create an Entity Framework 6.1.3 project. 
Read an entity from Database. 
Put a breakpoint at the object returned. If you can't see the Entity class as it is. The class name would be something like this 

System.Data.Entity.DynamicProxies.EnterpriseProfile_53366BBAB15B8167278E6798A23FA3DFC8A4CED175D940EFE7F18960B79076DE

My actual class name is EnterpriseProfile. But, the entity framework creates object of the type a proxy class with the above name to return. When you pass this object as a source to Tiny Mapper, you will get an the error as "calling convention must be varargs". 

Thats it...

If you still want the source and target classes, I will post again. Thanks!

**Comment by roshan-kumar001** [comment]
@technicalganesh: Can you please post the source and target classes? Thanks.
