### ISSUE TITLE
Bind Method with Type parameters

### ISSUE THREAD

**Issue by KuhTee** [TinyMapper/TinyMapper#29]
Hi,

really nice project.

I think it would be useful to have a Bind-Method which can be used without generics, for cases when the types are not known at compile time. Like this:
`public static void Bind(Type sourceType, Type targetType)`
`{`
`TypePair typePair = TypePair.Create(sourceType, targetType);`
`_mappers[typePair] = _targetMapperBuilder.Build(typePair);`
`}`

**Comment by GSerjo** [comment]
Thanks :)

Hm... looks like these methods are similar

`Bind(Type sourceType, Type targetType)`

`Bind<TSource, TTarget>()`

in both cases, type is required the difference only to call appropriate method

**Comment by cocosip** [comment]
Although these methods are similar,but i think it's better to support this method.
 Bind(Type sourceType, Type targetType)

**Comment by KuhTee** [comment]
Hello GSerjo,

the methods are similare, but not the same. Using
`Bind(Type sourceType, Type targetType)`
it's possible to set the binding at runtime. There are situations, where the actual types for binding are not known at compile time.

**Comment by cuibty** [comment]
+1

**Comment by GSerjo** [comment]
done
