### ISSUE TITLE
Not compatible with WUP Apps targeting Win10

### ISSUE THREAD

**Issue by StargazerNC** [TinyMapper/TinyMapper#30]
When trying to add the nuget package to a WUP project targeting Windows 10 (.NET Core), it fails and there's several messages like this one:

Install-Package : Some packages are not compatible with UAP,Version=v10.0 (win10-x64).
At line:1 char:1
- Install-Package TinyMapper
- ~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by GSerjo** [comment]
now should work
