### ISSUE TITLE
Unable bind members with different names/types

### ISSUE THREAD

**Issue by ericsans** [TinyMapper/TinyMapper#31]
Hello,
I used tinymapper version : 2.0.8 for framework 3.5, I get in trouble when making binding members with difference names.
The following code : 

1. Interface
```C#
public interface IObjectCategoryDetail : IAppView { 
   int    Identity { get; set; }
   string Codes { get; set; }
   string CategoryName { get; set; }
   string Comment { get; set; }
   bool   InActive	 { get; set; }
}
```

2. Class 
```C#
public class ObjectCategoryModel {
   public int    Identity { get; set; }
   public string Code { get; set; }
   public string CategoryName  { get; set; }
   public string Comment { get; set; }
   public bool   InActive { get; set; }
}
```

3. Bind & Mapping
```C#
TinyMapper.Bind<IObjectCategoryDetail, ObjectCategoryModel>(config => {
   config.Bind(source => source.Codes, target => target.Code);
});
ObjectCategoryModel __data = TinyMapper.Map<ObjectCategoryModel>(View);
```

the value of code (ObjectCategoryModel) after map always null, did I make mistake ?

Best regards,
Eric Santoso

**Comment by GSerjo** [comment]
Hello Eric,

To describe this behavior, I have to say a bit how `TinyMapper `saves class mapper. When `TinyMapper.Bind<IObjectCategoryDetail, ObjectCategoryModel>` was called `TinyMapper` creates a mapper class and put it to the dictionary where key is `<IObjectCategoryDetail, ObjectCategoryModel>`. 

So, when `TinyMapper.Map<ObjectCategoryModel>(View)` is called `TinyMapper` tries to find the mapper class by a key, but `View` type doesn't equal `IObjectCategoryDetail` (`TinyMapper` calls `view.GetType()`, as a result, `TinyMapper` doesn't find a mapper class and creates it on the fly but now without `config.Bind(source => source.Codes, target => target.Code)`

How to fix, just use method `TinyMapper.Map<IObjectCategoryDetail, ObjectCategoryModel>(View);` in this case `TinyMapper` gets the key threw generic types.

**Comment by ericsans** [comment]
Hello,

Thank you. Everything looks good . 

Best regards,
Eric Santoso
