### ISSUE TITLE
TinyMapper mapping with list of entity object

### ISSUE THREAD

**Issue by ronakjIndusa** [TinyMapper/TinyMapper#32]
I have started using TinyMapper in my project for object-to-object mapping and got succeeded for single object to single object mapping but i stuck when i want to map the whole list of entity object to list of DTO class. Can you please help me out. I googled but didn't find any solution. Can anyone please help me out?

I am able to map single object to object by using below code:
```
var sq = new SurveyQuestion
            {
                SurveyId = 61,
                Question = "John",
                QuestionDescription = "Doe",
                Type = "DB",
                Selector = "TB",
                QuestionId = "QID1",
                SubSelector = "TX"
             }
TinyMapper.Bind<Survey, surveyDto>();
var result = TinyMapper.Map<surveyDto>(sq);
```
But i stuck when i want to map whole list of survey entity to surveyDto entity:
````
List<Survey> survey = _surveyRepository.All().ToList();
TinyMapper.Bind<List<Survey>, List<SurveyDto>>();
List<SurveyDto> surveyDto = TinyMapper.Map<List<SurveyDto>>(survey);
```
gives below error:

Cannot implicitly convert type `System.Collections.Generic.List<SurveyDto>' to 'SurveyDto'`

**Comment by GSerjo** [comment]
I'm not sure that understand what are you going to bind. Do you want to map `List<T>` to a single object? Could you please provide full code, unfortunately, your sample has some missing parts, it's not clear what parameters in the `Bind` method

**Comment by ronakjIndusa** [comment]
Exactly, what you understand is right!!
I want to Map List<T> to List<V> where T is entity Object and V is my DTO object.
Here I have bind ` List<T>` to `List<V> `
```
List <Survey> sql= _surveyRepository.All().ToList(); //Getting all data from my table in List form
TinyMapper.Bind<List<Survey>, List<SurveyDto>>();
```
Can you please provide me the steps to map these two list?
Both below lines gives me error.
```
List<SurveyDto> surveyDto =  TinyMapper.Map<List<Survey>, List<SurveyDto>>(sql); //Error
List<SurveyDto> surveyDto = TinyMapper.Map<List<Survey>>(sql); //Error
```
Can you please suggest Mapping code?

**Comment by GSerjo** [comment]
yes, sure. 


Call this lines some where in the application start
```
TinyMapper.Bind<List<Survey>, List<SurveyDto>>();
```
then in you logic
```
List <Survey> sql= _surveyRepository.All().ToList();
List<SurveyDto> surveyDto = TinyMapper.Map<List<Survey>>(sql);
```

here the working sample

```
        [Fact]
        public void Test()
        {
            var fromDatabase = new List<Survey>
            {
                new Survey { Id = 1, Data = "Data1" },
                new Survey { Id = 2, Data = "Data2" }
            };

            TinyMapper.Bind<List<Survey>, List<SurveyDto>>();

            var dto = TinyMapper.Map<List<SurveyDto>>(fromDatabase);
        }


        public sealed class Survey
        {
            public int Id { get; set; }
            public string Data { get; set; }
        }


        public sealed class SurveyDto
        {
            public int Id { get; set; }
            public string Data { get; set; }
        }
```

**Comment by ronakjIndusa** [comment]
Many thanks for the example!! :+1:  Now am able to do collection mapping successfully.
@GSerjo One more point, Can you please let me know the drawback of using TinyMapper for object to object mapping, if there is any??
and why do we use Tinymapper instead of Automapper? which one is more better for object to object mapping in overall perspective?

Thanks for raising helping hands!!

**Comment by GSerjo** [comment]
There are spots even in the sun :) As for me, there are following pros and cons:

**TinyMapper**

Pros:
- Speed
- Really simple API

Cons:
- Doesn't have huge amount of mappings

**AutoMapper**

Pros:
- Huge amount of mapping rules

Cons:
- Speed
- _Huge amount of mapping rules_

I added "Huge amount of mappings" to pros and cons in `AutoMapper` because sometimes object mapper used as a part of business logic and a code becomes too complicated. So when you don't have the option to write business logic mapping in an object mapper, a code could be clear. On the other side, some applications can have really difficult mapping rules, so the `AutoMapper` could be a good choice. 

So, it depends on the exact issue, maybe even using several mappers could be a good decision.

**Comment by ronakjIndusa** [comment]
@GSerjo  Thanks for the detailed information!!
Is there any issue in using `Tinymapper` when we just want to map entity object to DTO object and then DTO object to ViewModel object in application when we have simple table schema with reference tables?

**Comment by ronakjIndusa** [comment]
@GSerjo I am getting below exception when I try to map below two objects:
Exception: {"Not suppoerted From ICollection`1 To ICollection`1"}

```
Example:
//Target Class
public class SurveyDto 
    {
        public long SurveyId { get; set; }
        public string SurveyName { get; set; }
        public string OwnerId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string Language { get; set; }

        public virtual ICollection<SurveyQuestionDto> SurveyQuestions { get; set; }
    }

//Source Class
public partial class Survey
    {
        public Survey()
        {
            this.SurveyQuestions = new HashSet<SurveyQuestion>();
        }
    
        public long SurveyId { get; set; }
        public string SurveyName { get; set; }
        public string OwnerId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string Language { get; set; }
    
        public virtual ICollection<SurveyQuestion> SurveyQuestions { get; set; }
    }

In Controller:
public void GetAll()
        {
            List<Survey> survey = _surveyRepository.All().ToList();
            TinyMapper.Bind<List<Survey>, List<SurveyDto>>();
            List<SurveyDto> surveyDto = TinyMapper.Map<List<SurveyDto>>(survey); //Getting exception
        }
```

Please help me out.

**Comment by GSerjo** [comment]
The exception occurred because `TinyMapper` doesn't know how to map `ICollection` to `ICollectction`, i.e. it doesn't know what exact type to create (is it `List<T>`, `Collection<T>`, `HashSet` or etc), the same like write this code by hands. So just let `TinyMapper` know what to create, for instance.

```
        [Fact]
        public void Map_ConcreteType_Success()
        {
            TinyMapper.Bind<Source2, Target2>(config =>
            {
                config.Bind(target => target.Ints, typeof(List<int>));
                config.Bind(target => target.Strings, typeof(List<string>));
            });

            var source = new Source2
            {
                Ints = new List<int> { 1, 2, 3 },
                Strings = new List<string> { "A", "B", "C" }
            };

            var actual = TinyMapper.Map<Target2>(source);
            Assert.Equal(source.Ints, actual.Ints);
            Assert.Equal(source.Strings, actual.Strings);
        }

        public class Source2
        {
            public IList<int> Ints { get; set; }
            public List<string> Strings { get; set; }
        }

        public class Target2
        {
            public IList<int> Ints { get; set; }
            public IEnumerable<string> Strings { get; set; }
        }
```
