### ISSUE TITLE
TinyMapper Reference Loop

### ISSUE THREAD

**Issue by xihu69** [TinyMapper/TinyMapper#34]
**Reference Loop Handling ?**

**Comment by maurosampietro** [comment]
UltraMapper is a new mapper conceived to handle references the right way, unlike any other mapper available today. Give it a try. https://github.com/maurosampietro/UltraMapper

**Comment by GSerjo** [comment]
thanks!

fixed https://github.com/TinyMapper/TinyMapper/releases/tag/v2.1.4-beta
