### ISSUE TITLE
Mapping Simple Object to  Complex Type 

### ISSUE THREAD

**Issue by ericsans** [TinyMapper/TinyMapper#36]
Hello,

I came back with some questions, i try to mapping a 
Simple To Complex Type or Complex Type To Simple
The following code : 
1. Class Person

``` C#
public class Person {
 public int Identity { get; set; }
 public string Code { get; set; }
 public string Name { get; set; }
 public string Address { get; set; }
 public string Phone { get; set; }
}
```
1. Class PersonDto

``` C#
public class PersonDto {
 public int Identity { get; set; }
 public string Code { get; set; }
 public string Name { get; set; }
 public AddressDto Address { get; set; }
}
```
1.  Class Address

``` C#
public class AddressDto {
 public string Address { get; set; }
 public string Phone { get; set; }
}
```
1. I try to Bind & Mapping like this 

``` C#
TinyMapper.Bind<SimpleToComplexEntity.Person, SimpleToComplexEntity.PersonDto>(
 config => {
  config.Bind(source => source.Address, target => target.Address.Address);
  config.Bind(source => source.Phone, target => target.Address.Phone);
 }
);
var personDto = TinyMapper.Map<SimpleToComplexEntity.PersonDto>(person);
```

when tyr to map `person` to `personDto`, i get an some error : Unable to cast object of type 'System.String' to type '[Name Space].AddressDto'.
What should I do ? so that mapping from `person` to `personDto` can be done.
Without the use of custom mapping example

Best regards,
Eric Santoso

**Comment by GSerjo** [comment]
You can create a [`TypeConverter`] (https://github.com/TinyMapper/TinyMapper/wiki/Custom-mapping) between `Person` and `PersonDto`. Unfortunately,  `TinyMapper` can't jump thru several dots (I mean types), like this one `target.Address.Address`, but I can add this behavior if it's necessary.

**Comment by ericsans** [comment]
Dear GSerjo,
sorry, I was late to respond, I think this will be a feature that is quite helpful

Best regards,
Eric Santoso

**Comment by strider77** [comment]
Hi GSerjo
I would appreciate the "several dots" feature as well

Kind regards
Pieter
