### ISSUE TITLE
Add interface to TinyMapper

### ISSUE THREAD

**Issue by treformat** [TinyMapper/TinyMapper#4]
Add interface to TinyMapper. It is necessary to mock TinyMapper and write tests for some sourcecode whitch use TinyMapper library.

**Comment by GSerjo** [comment]
You can create your own interface and it'll be more correct, so your code will not depend from any mapper (TinyMapper, AutoMapper or etc) You can easily change mapping behavior

    public sealed class ObjectMapper : IObjectMapper
    {
        public void Bind<TSource, TTarget>()
        {
            TinyMapper.Bind<TSource, TTarget>();
        }

        public void Bind<TSource, TTarget>(Action<IBindingConfig<TTarget>> config)
        {
            TinyMapper.Bind<TSource, TTarget>(config);
        }

        public TTarget Map<TSource, TTarget>(TSource source, TTarget target = default(TTarget))
        {
            return TinyMapper.Map(source, target);
        }

        public TTarget Map<TTarget>(object source)
        {
            return TinyMapper.Map<TTarget>(source);
        }
    }


    public interface IObjectMapper
    {
        void Bind<TSource, TTarget>();
        void Bind<TSource, TTarget>(Action<IBindingConfig<TTarget>> config);
        TTarget Map<TSource, TTarget>(TSource source, TTarget target = default(TTarget));
        TTarget Map<TTarget>(object source);
    }

**Comment by treformat** [comment]
Thanks for answer. You have right, i can create own interface IObjectMapper (like in Your example) and simple implementation which use TinyMapper :), but... in really world who do that? All people tall, use abstraction for databases, ORMs, IoCs, but... who do that? :) I don't know any project which for examples switch from MS SQL to Oracle, move from Entity Framework to NHibernate, change IoC from Ninject to Unity. The truth is when You chose some of technology/framework you will probably use it to the end of project.
The other topic is, it is quite hard to define universal interface (abstraction) for some kind library (like object mapping). In Your example the second method with signature ```public void Bind<TSource, TTarget>(Action<IBindingConfig<TTarget>> config)``` use specified for TinyMapper ```IBindingConfig``` interface.
So in my opinion the build-in interface for TinyMaper class will make some positives side.

**Comment by GSerjo** [comment]
Well done! About framework/library abstraction.
For example. For ORM abstraction, we've repository pattern, so other code don't know about ORM. The same for IoC, only [composition root](http://blog.ploeh.dk/2011/07/28/CompositionRoot/) knows about IoC. May be you'll use a framework to the end of the project and may be not.

In out projects we've changed EF on dapper (EF is too slow), Unity on Ninject (Uniny has not enough functions), RhinoMock on Moq (RhinoMock has not enough support). Now we're going to change Sql server on Mongodb.
