### ISSUE TITLE
Mapping for inner types not workin

### ISSUE THREAD

**Issue by asadaries** [TinyMapper/TinyMapper#44]
Hi, 
Below is my code to map object
TinyMapper.Bind<DataAccess.CustomerContact, CustomerContact>(config =>
            {
                config.Bind(x=>x.User.TenantId, x=>x.TenantId);
                config.Bind(x=>x.User.EmailAddress, x=>x.EmailAddress);
                config.Bind(x=>x.User.FirstName, x=>x.FirstName);
                config.Bind(x=>x.User.LastName, x=>x.LastName);
            });
            return TinyMapper.Map<CustomerContact>(user);

As you can see i am trying to bind the property with an inner object from source to destination, but this isn't working. Those values are shown as null after conversion, but i have values in original object used for conversion.

**Comment by MercedeX** [comment]
I'm facing the same issue. I have the following code. 

            TinyMapper.Bind<E.Post, V.Post>(c =>
            {
                c.Bind(s => s.PostId, t => t.Id);
                c.Bind(s => s.PostName, t => t.Title);
                c.Bind(s => s.Description, t => t.Description);
                c.Bind(s => s.Education, t => t.Education);
                c.Bind(s => s.Experience, t => t.Experience);
                c.Bind(s => s.TrainingRequired, t => t.IsTrainingRequired);
            });

but when I do this:
var  model = items.Select(x => TinyMapper.Map<ViewModels.Post>(x)).ToList();

I do not get any values for Id and Title. Is it because it is limited to the properties with the same name? What is the solution?

**Comment by GSerjo** [comment]
https://github.com/TinyMapper/TinyMapper/releases/tag/v2.1.3-beta
