### ISSUE TITLE
TinyMapper doesn't support IEnumerable<T>

### ISSUE THREAD

**Issue by Douglas2014** [TinyMapper/TinyMapper#47]
For example, we have the following classes:
public class PersonComplex
{
    public IEnumerable<string> Emails { get; set; }
    public string FirstName { get; set; }
    public Guid Id { get; set; }
    public string LastName { get; set; }
    public string Nickname { get; set; }
}

And bind IEnumerableof emails to List:
config.Bind(target => target.Emails, typeof(List<string>));

Then TypeExtensions.GetCollectionItemType throws NotSupportedException

A bug exists in the method TypeExtensions.IsIEnumerableOf.

Bug fixes like this:
public static bool IsIEnumerableOf(this Type type)
        {
            return type.IsGenericType && type.GetGenericTypeDefinition() == typeof(IEnumerable<>) ||
                   type.GetInterfaces()
                       .Any(x => x.IsGenericType && x.GetGenericTypeDefinition() == typeof(IEnumerable<>));
        }

**Comment by csaam** [comment]
Also add 

if  (targetType.IsGenericType && targetType.GetGenericTypeDefinition() == typeof(IEnumerable<>))
            {
                return EnumerableToList(enumerable);

            }

to the end of MapCore in the CollectionMapper
and 

else
            {
                EmitEnumerableToList(parentType, typeBuilder, typePair);
            }

to the builder BuildCore.  So that by default the enumtolist is emittted.
