### ISSUE TITLE
Should I call Bind for each Map call? 

### ISSUE THREAD

**Issue by iamkarlson** [TinyMapper/TinyMapper#48]
I've just started using TinyMapper and wondered how it works. It's like magic! Everything works! But I'm not sure if I don't call Bind method for each of my types couple, is it still working the same incredibile fast as with. Who can advise my what is a proper way to use this mapper? 
Also, I would appreciate if you give me suggestion where I can place all these bindings in WebAPI project? Now, I don't use bindings except when I need to ignore fields or create custom mapping.

**Comment by GSerjo** [comment]
`Bind` generate a mapping code and should be called once, but it's not an issue if call it twice or more, but no need to call it more than one.

Nice place to call `Bind`  is on application start
