### ISSUE TITLE
mapping ICollection to ICollection

### ISSUE THREAD

**Issue by fardani** [TinyMapper/TinyMapper#5]
ive got exception when tried to map ICollection type

An exception of type 'System.NotSupportedException' occurred in TinyMapper.dll but was not handled in user code

Additional information: Not suppoerted From ICollection`1 To ICollection`1

is there any way to do that?

**Comment by GSerjo** [comment]
`ICollection` is the base interface for many classes, `TinyMapper` doesn't know target collection type. The type is known only at runtime.

**Comment by GSerjo** [comment]
You can create your custom mapping. For instance

    public sealed class ForTests
    {
        [Fact]
        public void Test()
        {
            var source = new Source
            {
                Collection = new List<int> { 1, 2, 3 }
            };

            TinyMapper.Bind<Source, Target>();

            var target = TinyMapper.Map<Target>(source);
        }

        [TypeConverter(typeof(SourceConverter))]
        public sealed class Source
        {
            public ICollection Collection { get; set; }
        }

        public sealed class SourceConverter : TypeConverter
        {
            public override bool CanConvertTo(ITypeDescriptorContext context, Type destinationType)
            {
                return destinationType == typeof(Target);
            }

            public override object ConvertTo(ITypeDescriptorContext context, CultureInfo culture, object value, Type destinationType)
            {
                var concreteValue = (Source)value;
                var result = new Target
                {
                    Collection = new List<int>((IEnumerable<int>)concreteValue.Collection)
                };
                return result;
            }
        }

        public sealed class Target
        {
            public ICollection Collection { get; set; }
        }
    }

Here's more about [custom mapping](https://github.com/TinyMapper/TinyMapper/wiki/Custom-mapping)

**Comment by fardani** [comment]
Great, Thanks
