### ISSUE TITLE
Hi  will you use dotnet core?

### ISSUE THREAD

**Issue by zuosc** [TinyMapper/TinyMapper#58]
I try use dot net core rewrite TinyMapper。  but I know  little about  ‘Emit’ 。。。

when  I use ‘typeBuilder.CreateTypeInfo()’  replace ‘typeBuilder.CreateType()’，  it's error...

System.TypeLoadException:“Access is denied: 'Nelibur.ObjectMapper.Mappers.Classes.ClassMapper`2[Benchmark.Benchmarks.PrimitiveTypeBenchmark+Source,Benchmark.Benchmarks.PrimitiveTypeBenchmark+Target]'.”

`

protected override Mapper BuildCore(TypePair typePair)
        {
            Type parentType = typeof(ClassMapper<,>).MakeGenericType(typePair.Source, typePair.Target);
            TypeBuilder typeBuilder = _assembly.DefineType(GetMapperFullName(), parentType);
            EmitCreateTargetInstance(typePair.Target, typeBuilder);
            Option<MapperCache> mappers = EmitMapClass(typePair, typeBuilder);
            var tmp = typeBuilder.CreateTypeInfo();
            var result = (Mapper)Activator.CreateInstance(typeBuilder.CreateTypeInfo().AsType());
            mappers.Do(x => result.AddMappers(x.Mappers));
            return result;
        }

`

SO, I do not know how to solve it。。。

you  will  help me？

**Comment by GSerjo** [comment]
Hi Zuosc, 

Could you please share your branch, I'll take a look.

BTW current version of TinyMapper doesn't support .net core, but in one day, it definitely will :)

**Comment by zuosc** [comment]
you can see  https://github.com/zuosc/TinyMapper.Core

**Comment by GSerjo** [comment]
converted to .net core
