### ISSUE TITLE
Support mapping collection properties without using TypeConverter

### ISSUE THREAD

**Issue by cvetomirtodorov** [TinyMapper/TinyMapper#6]
This is more of a feature request rather than an issue.

Yes - TinyMapper seems to be much faster than AutoMapper. But the problem is that your complex mapping approach eliminates the need for using an object mapper. If I want to map objects containing collections I'd rather do a manual mapping method than creating a `TypeConverter`.

So, bottom line is that I want to map classes like these:

    class Parent 
    {
      public Parent()
      {
        Children = new List<Child>();
      }
      public string Name {get;set;}
      public List<Child> Children {get;private set;}
    }
    
    class Child
    {
      public string Name {get;set;}
    }

**without** using a `TypeConverter`.

**Comment by StargazerNC** [comment]
+1 hee for this. Tinymapper seems to be the answer for my prayers. AutoMapper and ValueInjection was the ones I've been using, but performance is key and Tiny is fast!

But the support for collections is in fact, not ideal. 

Looking forward for this! :)

**Comment by GSerjo** [comment]
Guys, thanks for the feedback. All work nice If `Source` and `Target` has the same collection, i.e.

    public class Source
    {
        public List<string> Names { get; set; }
    }

    public class Target
    {
        public List<string> Names { get; set; }
    }

Another sample

    public class Source
    {
        public List<Person> Persons { get; set; }
    }

    public class Target
    {
        public List<string> Names { get; set; }
    }

    public class Person
    {
        public string Name { get; set; }
    }

Do you want to map `Persons` to `Names` without `TypeConverter`?

**Comment by StargazerNC** [comment]
In my case, what I would like to do (can do it on ValueInjecter, no quite sure on AutoMapper) is mapping an object to a dto. something along the lines:

```cs
public class Person
{
    public List<Contact> Contacts { get; set; }
}

public class PersonDTO
{
    public List<ContacDTO> Contacts { get; set; }
}
```

ValueInjecter as the nice thing about it that let's you construct your injections to fit virtually every scenario. I think AutoMapper has something for this also. How could one achieve this with TinyMappper, besides using TypeConverters?

Some sort of convention based mapping would suffice for me, I guess.

**Comment by GSerjo** [comment]
For instance you have following code

        public class Person
        {
            public List<Contact> Contacts { get; set; }
        }

        public class PersonDto
        {
            public List<ContactDto> Contacts { get; set; }
        }

        public class Contact
        {
            public int Int { get; set; }
            public string String { get; set; }
        }

        public class ContactDto
        {
            public int Int { get; set; }
            public string String { get; set; }
        }

you can do like this

            TinyMapper.Bind<Person, PersonDto>();

            var source = new Person
            {
                Contacts = new List<Contact>
                {
                    new Contact
                    {
                        Int = 1,
                        String = "2"
                    }
                }
            };

            var actual = TinyMapper.Map<PersonDto>(source);

**Comment by StargazerNC** [comment]
I've tried that. The collections don't get mapped. Maybe it has to do with the non DTO classes being tracked entities of the ORM tool OpenAccess from Telerik?

**Comment by GSerjo** [comment]
Hmm, maybe, could you please give your `Person` and `PersonDto` classes. I'll try to reproduce the issue.

**Comment by StargazerNC** [comment]
Hi!

Well, I can do better, if you prefer and is ok for you. I may send you the sample project I'm using to test TinyMapper which is using OpenAccess ORM so you can see what I mean. 

Let me know if this is ok for you.

**Comment by GSerjo** [comment]
Yes, it's ok

**Comment by StargazerNC** [comment]
I'll upload it later to my account an let you know then, ok?

Thanks!

**Comment by GSerjo** [comment]
Yes, of course. You're welcome

**Comment by StargazerNC** [comment]
Hello @GSerjo 

Sorry on the delay, couldn't pay attention to this sooner. In the link below you can find my tests.

https://github.com/StargazerNC/TinyMapperTests/tree/master

**Comment by GSerjo** [comment]
Thank you, I really appreciate your feedback.

The `Person` two issues: 

1. The class has only `get` property

```cs
private IList<Contact> _contacts = new List<Contact>();
public virtual IList<Contact> Contacts
{
	get
	{
		return this._contacts;
	}
}
```
TinyMapper maps only public fields and properties with `set` accessor, i.e. TinyMapper tries create and set a new property object.

2. `Contacts` it's `IList<T>` so TinyMapper has to know concrete type class, i.e. for instance it could be `List<T>`, `Collection<T>` and etc. Concrete class type is available only at runtime. That's why `TypeConverter` is needed.

I see following workaround:

1. Change `IList` on `List` with set
2. Create custom `TypeConverter`
3. Improve TinyMapper, so it'll check collection on `null` if it has no `set` accessor and add items. I'll teach TinyMapper to know this kind of mapping.

**Comment by StargazerNC** [comment]
I'll do those modifications and let you know. Nevertheless, the Lists properties are autogenerated by Telerik's OpenAccess so I might have an issue there, we'll see. 

Thanks!

**Comment by oryol** [comment]
I understand setter and concrete type requirements for target type. But why it's required for source type? For example, if I have in source type ```IReadOnlyList<SomeEntity>``` why I can't map it to the ```SomeEntityModel[]``` (it crashes in the ```Type sourceItemType = typePair.Source.GetCollectionItemType();```)

**Comment by GSerjo** [comment]
Oryol,

Absolutily agree, concrete type is not required for source type.

This method crashes

        public static Type GetCollectionItemType(this Type type)
        {
            if (type.IsArray)
            {
                return type.GetElementType();
            }
            else if (type.IsListOf()) - the problem is here, it's too strong requirement
            {
                return type.GetGenericArguments().First();
            }
            throw new NotSupportedException();
        }

I've changed on `type.IsIEnumerableOf()` and all works properly. Thanks a lot.

**Comment by GSerjo** [comment]
TinyMapper allows to set concrete type if required, i.e.

        public class Source
        {
            public IList<int> Ints { get; set; }
            public List<string> Strings { get; set; }
        }

        public class Target
        {
            public List<int> Ints { get; set; }
            public IEnumerable<string> Strings { get; set; }
        }

         TinyMapper.Bind<Source, Target>(config =>
            {
                config.Bind(target => target.Strings, typeof(List<string>));
            });
