### ISSUE TITLE
Map properties to existing object

### ISSUE THREAD

**Issue by ChaosD** [TinyMapper/TinyMapper#67]
Is it possible to map properties to an existing object?

For an update operation, i receive a DTO and need to map its properties to a tracked entity from Entity Framework

Sample snippet:
```
Shop tracked = WriteContext.Shops.Single(s => s.Guid == shopDTO.guid);
tracked.Name    = shopDTO.Name;
tracked.Vendor  = shopDTO.Vendor;
 ... 
// Todo: map properties in tinymapper
WriteContext.SaveChanges();
```

It is important to update the properties in the tracked object, otherwise it will not get written to the database.

**Comment by GSerjo** [comment]
Hi ChaosD,

looks like you are looking this behavior

```
TinyMapper.Bind<Person, PersonDto>(config =>
{
	config.Ignore(x => x.Id);
	config.Ignore(x => x.Email);
	config.Bind(source => source.LastName, target => target.Surname);
	config.Bind(target => source.Emails, typeof(List<string>));
});

var person = new Person
{
	Id = Guid.NewGuid(),
	FirstName = "John",
	LastName = "Doe",
	Emails = new List<string>{"support@tinymapper.net", "MyEmail@tinymapper.net"}
};

var personDto = TinyMapper.Map<PersonDto>(person);
```

**Comment by ChaosD** [comment]
Thank you for your answer, @GSerjo 

If i understand you correctly, this would allow Tinymapper to create a **new** PersonDto mapped from the person object. My case is a little bit different (pseudocode):

```
var updatePersonDto = ... (from request)
var personToUpdate = GetPersonFromDatabase(name: "GSerjo");

Tinymapper.Apply(personToUpdate , updatePersonDto );
personToUpdate .SaveToDatabase()
```

The reason for this is that Entity Framework tracks the returned `person`, so it can be saved again after manipulating properties. For now, i fetch a tracked entity, manually set all the properties from the DTO and then save it. I hope to automate this process using TinyMapper, because all the mappings already exist.

**Comment by GSerjo** [comment]
oh, I see, just update already existing object. When do you need it? :)

**Comment by ChaosD** [comment]
We are using entity framework, which can track results returned from a query (see: https://docs.microsoft.com/en-us/ef/core/querying/tracking) 

This means, that if the object gets modified, it can be easily saved back to the database. My question is, if Tinymapper could do the modification to the existing object somehow.

**Comment by GSerjo** [comment]
Yes, try to use this method. 

`public static TTarget Map<TSource, TTarget>(TSource source, TTarget target = default(TTarget))`

**Comment by ChaosD** [comment]
Ohhh, i missed that one. Thank you!
