### ISSUE TITLE
How can we map between fields with different names?

### ISSUE THREAD

**Issue by dougclutter** [TinyMapper/TinyMapper#7]

**Comment by GSerjo** [comment]
You can map thru TypeConverter, here's you can find more [samples](https://github.com/TinyMapper/TinyMapper/wiki/Custom-mapping)

**Comment by GSerjo** [comment]
I'm going to add something like this.

            var source = new Source
            {
                MyInt = 1,
                MyString = "My Value"
            };

            TinyMapper.Bind<Source, Target>(config =>
            {
                config.Bind(from => from.MyInt, to => to.Int);
                config.Bind(from => from.MyString, to => to.MyString);
            });

            var target = TinyMapper.Map<Target>(source);

**Comment by GSerjo** [comment]
Could you please take a look on the 2.0.0 version. You can bind like this one

```csharp
TinyMapper.Bind<Person, PersonDto>(config =>
{
	config.Ignore(x => x.Id);
	config.Ignore(x => x.Email);
	config.Bind(source => source.LastName, target => target.Surname);
});
```

**Comment by dougclutter** [comment]
This appears to address the concern I raised in this issue.  Thanks!
