### ISSUE TITLE
Is it possible to add a non-generic Map method?

### ISSUE THREAD

**Issue by izaruba** [TinyMapper/TinyMapper#71]
Currently there's no way to use TinyMapper as a runtime mapper but as a compile time only due to a generic `Map<TSource, TTarget>` kind.

The framework's infrastructure though allows to add a non-generic overload of `Map`, e.g.
```
public static object Map(Type sourceType, Type targetType, object source, object target = null)
{
    TypePair typePair = TypePair.Create(sourceType, targetType);

    Mapper mapper = GetMapper(typePair);
    var result = mapper.Map(source, target);

    return result;
}
```
Is there any chance for the non-generic `Map` method to be added?

**Comment by GSerjo** [comment]
Hi Izaruba ,

sure, will add today.

**Comment by izaruba** [comment]
Amazing! I appreciate so much!

**Comment by GSerjo** [comment]
Done, https://github.com/TinyMapper/TinyMapper/releases/tag/v3.0.2-beta

Happy coding :)
