### ISSUE TITLE
The type initializer for '...' threw an exception

### ISSUE THREAD

**Issue by spmorr01** [TinyMapper/TinyMapper#79]
Over the past year, we sporadically get these errors thrown in our application, which completely renders our app useless since we use TinyMapper for all of our DAL calls. The InnerException always points to the TinyMapper "Bind" method. Our only fix has been restarting our App Pool. Our code works fine 99% of the other times, and there aren't any changes we're making where these errors are getting thrown, so we suspect it to possibly be an issue within TinyMapper.

Here is a screenshot:

![image](https://user-images.githubusercontent.com/12806561/63892119-7706c100-c9ac-11e9-97ff-7badeb67de50.png)

**Comment by GSerjo** [comment]
Hi, @spmorr01 Looks likes the source data, `Key` or `Value` contains `null`.  i.e. your code trying to insert null as a `value` or `key`

**Comment by spmorr01** [comment]
I don't think that's right because as soon as we make a fake edit to our web config on the server, it works. This is loading the exact same webpage, so the data is the same in both instances

**Comment by GSerjo** [comment]
Hi, @spmorr01, maybe it's because the code is calling `Bind` incorrectly. i.e it's not thread-safe and should be called only once, for instance during an application start

**Comment by nzaugg** [comment]
Based on the stack trace, the options for the null reference are the key or the value. The value has no problem being null so it _has_ to be the key that is mapping to null.
