### ISSUE TITLE
Is it possible to map a generic Dictionary<T1,T2>?

### ISSUE THREAD

**Issue by str19** [TinyMapper/TinyMapper#9]

**Comment by GSerjo** [comment]
Not yet, but it's easy to add. Do you need it?

**Comment by GSerjo** [comment]
As workaround, you can create [`TypeConverter`](https://msdn.microsoft.com/en-us/library/ayybcxe5.aspx) for instance

    public sealed class DictionaryConverterSnippet
    {
        public DictionaryConverterSnippet()
        {
            var converterAttribute = new TypeConverterAttribute(typeof(DictionaryTypeConverter<string, string>));
            TypeDescriptor.AddAttributes(typeof(Dictionary<string, string>), converterAttribute);
        }

        [Fact]
        public void Converter()
        {
            TinyMapper.Bind<SourceClass, TargetClass>();

            var source = new SourceClass
            {
                Dictionary = new Dictionary<string, string> { { "key", "Value" } }
            };

            var result = TinyMapper.Map<TargetClass>(source);
        }

        public class SourceClass
        {
            public Dictionary<string, string> Dictionary { get; set; }
        }

        public class TargetClass
        {
            public Dictionary<string, string> Dictionary { get; set; }
        }

        private sealed class DictionaryTypeConverter<TKey, TValue> : TypeConverter
        {
            public override bool CanConvertFrom(ITypeDescriptorContext context, Type sourceType)
            {
                return sourceType == typeof(Dictionary<TKey, TValue>);
            }

            public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)
            {
                var concreteValue = (Dictionary<TKey, TValue>)value;
                var result = new Dictionary<TKey, TValue>();

                foreach (KeyValuePair<TKey, TValue> pair in concreteValue)
                {
                    result[pair.Key] = pair.Value;
                }

                return result;
            }
        }
    }

**Comment by str19** [comment]
Well, TypeConverter works, but there are some features.
I use TinyMapper in Unuty3d (mono runtime version: 2.0.50727.1433). TypeConverter does not work properly - the method CanConvertTo (Target) always returns false, respectively TypePair.HasTypeConverter() returns false. 
TypeConverter is a convenient solution, but is there a way to make it work on an outdated version of mono? It would be very cool, because mappers for Unity3d not there.

**Comment by GSerjo** [comment]
It's strange, should work on mono 2.0 too. Could you please share your type `converter`and `source` class with a dictionary.
I'm adding dictionary support without a `type converter`

**Comment by GSerjo** [comment]
Take new version 1.0.22  from nuget.org, all should work without the `TypeConverter`

**Comment by str19** [comment]
Great, tnx!
I figured out what the problem is with TypeConverter - not binding works through a converter TypeDescriptor.AddAttributes() If you use the class attribute that's all right.
https://github.com/str19/TinyMapperCustomConverter/blob/master/DictExample.cs

**Comment by GSerjo** [comment]
Хм, забавно.. 
Всегда пожалуйста :)
